{
  "comments": [
    {
      "key": {
        "uuid": "8d030dfe_e1c60f3a",
        "filename": "src/config/api-server/vnc_cfg_api_server/api_server.py",
        "patchSetId": 9
      },
      "lineNbr": 5268,
      "author": {
        "id": 971
      },
      "writtenOn": "2020-10-27T05:01:13Z",
      "side": 1,
      "message": "I checked the logs, if using  @pipe_start_app.hook it\u0027s throwing \nAttributeError: \u0027AuthPreKeystone\u0027 object has no attribute \u0027hook\u0027.",
      "revId": "9bbf3e1f7cb31d6fc4739ad1a2780eadc1886614",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}